name: Make Release
on:
  push:
    branches:
      - jda5  # Adjust the branch name as needed

jobs:
  build_jar:
    name: Build Jar
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Set Version
        uses: datamonsters/replace-action@v2
        with:
          files: 'pom.xml'
          replacements: 'Snapshot=${{ github.sha }}'

      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify

      - name: Rename jar
        run: mv target/*-All.jar JMusicBot-${{ github.sha }}.jar

      - name: Upload jar
        uses: actions/upload-artifact@v3
        with:
          name: jar
          path: JMusicBot-${{ github.sha }}.jar
          if-no-files-found: error

  create_release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: build_jar
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download a Build Artifact
        uses: actions/download-artifact@v3.0.0
        with:
          name: jar
          path: .

      - name: Show Artifacts
        run: ls -R

      - name: Get Pushed Commits
        id: get_pushed_commits
        run: |
          commit_range="${{ github.event.before }}...${{ github.sha }}"
          commits=$(git log --pretty=format:'%h: %s' $commit_range)
          echo "commits=$commits" >> $GITHUB_ENV


      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.sha }}
          name: Version ${{ github.sha }}
          draft: true
          prerelease: false
          artifacts: "*.jar"
          body: |
            Commit: ${{ github.sha }}

            Commits:
            ${{ env.commits }}

            ---
            ### Setup
            https://jmusicbot.com/setup  
            https://jmusicbot.com/config  
            # Download: [JMusicBot-${{ github.sha }}.jar](https://github.com/ErdbeerbaerLP/MusicBot/releases/download/${{ github.sha }}/JMusicBot-${{ github.sha }}.jar)
